[package]
name = "html-parser"
version = "0.1.0"
authors = ["154852 <louisemileploix@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
tree = {path = "../tree"}